### PR TITLE
Support an optional name option for most constraints

### PR DESCRIPTION
**Pull request by pjungwir**

### CODE REVIEW

**Comment by nullobject** [comment]
Oops, I just realised that the `remove_*_constraint` function will need to be updated to support `name` also.

**Comment by pjungwir** [comment]
Good point! I'll give you a PR for that too... :-)

**Comment by nullobject** [comment]
All good, I've fixed it up already :)

**Comment by pjungwir** [comment]
Okay, great!

That PR for testing against a real database also adds an `options` hash to each `remove_*` method, so it might need rebasing now. Let me know over there what you think of it! I'm eager to work on revertible methods but want those tests first.

**Comment by nullobject** [comment]
Will do, I'm at work right now so I probably won't get a chance until later tonight.

**Pull request merged**
